title:              Ahmad's Blog
email:              ahsa9978@gmail.com
description:        Life of a Computer Engineering student at Iran's SUT.
author:             Ahmad Salimi
baseurl:            "/"
url:                "https://ahmadsalimi.github.io"

# Social Profiles
twitter_username:   ChichekaMan
github_username:    ahmadsalimi
facebook_username:  
instagram_username: ahmadsalimi__ 
linkedin_username:  ahmadsalimi

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
