name: Deploy github pages

on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: 16.4.1

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm run test

    - name: Checkout in build directory
      uses: actions/checkout@v2
      with:
        path: build
        ref: gh-pages

    - name: Build
      run: ls -a build; npm run build; ls -a build

    - name: Deploy
      run: |
        git config user.name $user_name
        git config user.email $user_email
        git add -A
        git commit -m "Deploy to GitHub Pages"
        git push origin gh-pages
      working-directory: build
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
